UNIT_NAMES: dict[int, str] = {
    1: "Fortress / 堡垒",
    2: "Marksman / 长弓",
    3: "Vulcan / 火神",
    4: "Melting Point / 熔点",
    5: "Rhino / 犀牛",
    6: "Wasp / 兵蜂",
    7: "Mustang / 野马",
    8: "Steel Ball / 钢球",
    9: "Fang / 尖牙",
    10: "Crawler / 爬虫",
    11: "Overlord / 霸主",
    12: "Stormcaller / 暴雨",
    13: "Sledgehammer / 铁锤",
    14: "Hacker / 骇客",
    15: "Arclight / 弧光",
    16: "Phoenix / 凤凰",
    17: "War Factory / 战争工厂",
    18: "Wraith / 恶灵",
    19: "Scorpion / 狂蝎",
    20: "Fire Badger / 火獾",
    21: "Sabertooth / 剑齿虎",
    22: "Typhoon / 台风",
    23: "Sandworm / 沙虫",
    24: "Tarantula / 狼蛛",
    25: "Phantom Ray / 鬼鳐",
    26: "Farseer / 先知",
    27: "Raiden / 雷霆",
    28: "Hound / 猎犬",
    29: "Abyss / 深渊",
    30: "Void Eye / 魔眼",
    31: "Vortex / 磁暴",
    2002: "Mountain / 泰山",
}


def unit_name(unit_id: int) -> str:
    return UNIT_NAMES.get(unit_id, f"Unknown / 未知单位 ({unit_id})")
